"""Health contracts: what each scheduled job must leave behind, checked by the
job itself as its last step and written where the board can read it.

Eleven of the fourteen failures of 2026-08/09 were runs that exited green and
produced nothing: a card build that died mid-sweep, a grading run that graded
zero picks, a scoring run whose inputs were 57 columns of NaN. GitHub's
failed-run email fires on none of those, and the gauges in `ops.py` say whether
the system CAN keep running, not whether the run that just finished DID what it
was for. A contract is that second question, written down as data:

    Contract  -- one per scheduled Neon-writing job (card, grade, sunday,
                 lines_watch): the workflow file, the artifacts the run must
                 leave, the env it is judged with, its checks, and the catalogue
                 of past failures each check would have caught.
    Check     -- ONE POSITIVE FACT about this run ("a cards row for this
                 season/week was written after the run started and carries this
                 slot"), with a severity: `failed` reddens the run (email),
                 `degraded` is board-only.
    evaluate  -- runs every check; the verdict is `failed` if any failed-severity
                 check misses, else `degraded` if any check misses, else `ok`.

scripts/health_check.py is the workflow step; it writes the verdict to the
`last_health_<job>` gauge (`ops.health_key`) with a <= 300-char note naming the
run, the trigger, the slot and every miss. web/lib/boardHealth.ts reads it into
the board banner and /api/health. docs/HEALTH.md carries the prose and a block
generated by `render_contracts()` (`python -m beatvegas.health --render-md
docs/HEALTH.md`); tests/test_docs_parity.py keeps the two equal.

Every timestamp here is NAIVE UTC, like every other timestamp in the database.
A check never raises: a check that cannot run is not a positive fact, so it is
reported as a miss with the exception's name in its detail.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Callable, Dict, List, Mapping, Optional, Set, Tuple

from .ci import CARD_STATUS_BY_SLOT, PAPER_WINDOW_HOURS, SCHEDULED_SLOTS, et_midnight_as_naive_utc
from .hardrock import HR_BOOK_KEY
from .ops import LAST_CLOSE_CAPTURE_AT, LAST_GRADE_COMPLETED_AT, read_gauge

# Literal["failed", "degraded"] / Literal["ok", "degraded", "failed"] -- kept as
# plain str aliases plus the tuples below so Python 3.9 callers can iterate them.
Severity = str
Verdict = str
SEVERITIES: Tuple[str, ...] = ("failed", "degraded")
VERDICTS: Tuple[str, ...] = ("ok", "degraded", "failed")

# --------------------------------------------------------------------------- #
# Parameters. Each is named in a check's `fact` as NAME [default] and rendered
# into docs/HEALTH.md, so a change here shows up in the doc diff.
# --------------------------------------------------------------------------- #
# A card with fewer Hard Rock-priced items than this is not a slate: Tuesday's
# build sees ~31% of ~82 games priced (2026 week 2), Saturday morning 97%.
HR_PRICED_FLOOR = 10
# A rated game with no final this long after kickoff missed at least one grading
# window. MUST equal web/lib/boardHealth.ts STALE_AFTER_HOURS (parity-tested).
STALE_AFTER_HOURS = 18
# Share of the week's FBS slate that must carry a pace row / a weather row.
PACE_COVERAGE_MIN = 0.8
WX_COVERAGE_MIN = 0.8
# The rule .github/actions/cfbd-cache-save applies: a reference file under this
# is the 2-byte empty payload season_stats._cached used to leave behind.
REFERENCE_CACHE_MIN_BYTES = 1024
# The note the gauge carries. app_settings.note is Text; the cap is for the
# banner, which shows the whole thing.
NOTE_MAX_CHARS = 300

PARAMETERS: Dict[str, Any] = {
    "HR_PRICED_FLOOR": HR_PRICED_FLOOR,
    "STALE_AFTER_HOURS": STALE_AFTER_HOURS,
    "PACE_COVERAGE_MIN": PACE_COVERAGE_MIN,
    "WX_COVERAGE_MIN": WX_COVERAGE_MIN,
    "REFERENCE_CACHE_MIN_BYTES": REFERENCE_CACHE_MIN_BYTES,
}

# The reference files beatvegas/sources/season_stats.py::_cached writes, one per
# season: sp_<yr>.json, talent_<yr>.json, roster_<yr>.json, returning_<yr>.json,
# adv_<yr>.json. The same five the cache-save action counts.
REFERENCE_CACHE_KINDS: Tuple[str, ...] = ("sp", "talent", "roster", "returning", "adv")
DERIVED_LINES_MODEL_VERSION = "derived_lines"
FULL_GAME_MARKET = "full_game_total"
FIRST_HALF_MARKET = "1H_total"


# --------------------------------------------------------------------------- #
# Data
# --------------------------------------------------------------------------- #
@dataclass
class Ctx:
    """Everything a check may read. `session` is an open SQLAlchemy session;
    `now` and `run_started_at` are naive UTC; `outcomes` maps a step name
    ("sweep", "preview", ...) to GitHub's step outcome ("success" / "failure" /
    "skipped" / "cancelled"); `status_files` holds the parsed JSON status files
    that exist ("sweep", "close"); `env` is the raw environment for details."""

    session: Any
    now: datetime
    job: str
    run_started_at: datetime
    season: Optional[int] = None
    week: Optional[int] = None
    slot: Optional[str] = None
    market: Optional[str] = None
    outcomes: Dict[str, str] = field(default_factory=dict)
    status_files: Dict[str, dict] = field(default_factory=dict)
    env: Mapping[str, str] = field(default_factory=dict)
    # Per-evaluation memo (the card row is read once for four checks).
    cache: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Result:
    ok: bool
    detail: str


@dataclass(frozen=True)
class Check:
    id: str
    severity: Severity
    fact: str
    fn: Callable[[Ctx], Result]


@dataclass(frozen=True)
class FailureMode:
    date: str
    what: str
    caught_by: Tuple[str, ...]


def _no_info(ctx: Ctx) -> Dict[str, str]:
    return {}


@dataclass(frozen=True)
class Contract:
    job: str
    workflow: str
    window: str
    artifacts: Tuple[str, ...]
    inputs: Tuple[str, ...]
    checks: Tuple[Check, ...]
    failure_modes: Tuple[FailureMode, ...]
    # Facts worth carrying in the note that are never a miss (an early_season
    # hold is the gate working, not the job failing).
    info: Callable[[Ctx], Dict[str, str]] = _no_info


# --------------------------------------------------------------------------- #
# Shared helpers
# --------------------------------------------------------------------------- #
def _clean(detail: str) -> str:
    """A detail must not carry the two characters the note format uses."""
    return detail.replace(";", ",").replace("\n", " ")


def _iso(d: Optional[datetime]) -> str:
    return "none" if d is None else d.replace(microsecond=0).isoformat()


def _parse_kick(raw: Optional[str]) -> Optional[datetime]:
    """A card item's `kick` (ISO, trailing Z) as naive UTC -- the same parse
    scripts/build_card.py::log_paper_picks applies."""
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw).replace("Z", "+00:00")).replace(tzinfo=None)
    except ValueError:
        return None


def _fbs_slate(ctx: Ctx) -> List[Tuple[int, str, str]]:
    """(game_id, home, away) for the week's FBS-vs-FBS games -- the set the
    scorer reads (etl/fbs.py). A season the snapshot does not cover falls back
    to every game of the week, with the fallback named in the memo."""
    if "fbs_slate" in ctx.cache:
        return ctx.cache["fbs_slate"]
    from .db.models import Game
    from .etl.fbs import load_fbs_teams

    rows = (
        ctx.session.query(Game.id, Game.home_team, Game.away_team)
        .filter(Game.season == ctx.season, Game.week == ctx.week)
        .all()
    )
    members: Optional[Set[str]] = None
    try:
        members = load_fbs_teams().get(int(ctx.season)) if ctx.season is not None else None
    except (FileNotFoundError, ValueError):
        members = None
    if members is None:
        ctx.cache["fbs_note"] = "no FBS snapshot for the season, counting every game"
        slate = [(int(g), h, a) for g, h, a in rows]
    else:
        ctx.cache["fbs_note"] = ""
        slate = [(int(g), h, a) for g, h, a in rows if h in members and a in members]
    ctx.cache["fbs_slate"] = slate
    return slate


def _reference_cache_populated(ctx: Ctx) -> Result:
    """The CFBD reference files the feature frame joins. The PRIOR season's five
    are the priors every scored row needs and are what the check demands; the
    current season's files are reported, not required -- season_stats._cached_soft
    documents that a season still being played may have no full-year aggregate
    to fetch, so an absent current-season file can be correct."""
    if ctx.season is None:
        return Result(False, "season unknown")
    from .sources.season_stats import CACHE

    def _ok(name: str) -> bool:
        p = CACHE / name
        return p.exists() and p.stat().st_size > REFERENCE_CACHE_MIN_BYTES

    prior = ctx.season - 1
    missing = [f"{k}_{prior}.json" for k in REFERENCE_CACHE_KINDS if not _ok(f"{k}_{prior}.json")]
    current = sum(1 for k in REFERENCE_CACHE_KINDS if _ok(f"{k}_{ctx.season}.json"))
    n = len(REFERENCE_CACHE_KINDS)
    detail = f"{prior}: {n - len(missing)}/{n} files >{REFERENCE_CACHE_MIN_BYTES}B"
    if missing:
        detail += " missing " + ",".join(missing)
    detail += f", {ctx.season}: {current}/{n}"
    return Result(not missing, detail)


# --------------------------------------------------------------------------- #
# card
# --------------------------------------------------------------------------- #
def _card_payload(ctx: Ctx) -> Optional[dict]:
    """The `cards` row this run wrote: (season, week), built after the run
    started, payload.slot == the resolved slot. Newest first; memoised."""
    if "card" in ctx.cache:
        return ctx.cache["card"]
    from .db.models import Card

    found: Optional[dict] = None
    if ctx.season is not None and ctx.week is not None:
        rows = (
            ctx.session.query(Card)
            .filter(
                Card.season == ctx.season,
                Card.week == ctx.week,
                Card.built_at >= ctx.run_started_at,
            )
            .order_by(Card.built_at.desc(), Card.id.desc())
            .all()
        )
        for row in rows:
            try:
                payload = json.loads(row.payload)
            except (TypeError, ValueError):
                continue
            if not isinstance(payload, dict):
                continue
            if ctx.slot is None or payload.get("slot") == ctx.slot:
                payload["_built_at"] = row.built_at
                found = payload
                break
    ctx.cache["card"] = found
    return found


def card_row_this_run(ctx: Ctx) -> Result:
    p = _card_payload(ctx)
    if p is None:
        return Result(
            False,
            f"no cards row for {ctx.season} w{ctx.week} slot={ctx.slot} "
            f"built since {_iso(ctx.run_started_at)}",
        )
    return Result(True, f"built_at={_iso(p.get('_built_at'))} items={len(p.get('items') or [])}")


def card_status_clean(ctx: Ctx) -> Result:
    p = _card_payload(ctx)
    if p is None:
        return Result(False, "no card row")
    expected = CARD_STATUS_BY_SLOT.get(ctx.slot or "")
    status = p.get("status")
    deg = p.get("degraded") or []
    names = ",".join(str(d.get("input", "?")) for d in deg if isinstance(d, dict))
    detail = f"status={status} (slot wants {expected}) degraded={len(deg)}"
    if names:
        detail += f" [{names}]"
    return Result(status == expected and not deg, detail)


def card_hr_priced_floor(ctx: Ctx) -> Result:
    p = _card_payload(ctx)
    if p is None:
        return Result(False, "no card row")
    n = sum(1 for it in p.get("items") or [] if it.get("hr_line") is not None)
    return Result(n >= HR_PRICED_FLOOR, f"{n} Hard Rock-priced items (floor {HR_PRICED_FLOOR})")


def card_paper_logged_iff_window(ctx: Ctx) -> Result:
    """A scheduled slot paper-logs every qualifying item inside its window
    (beatvegas/ci.py PAPER_WINDOW_HOURS; None = the rest of the week); `manual`
    logs nothing, because the first log of a game is the one that stays."""
    from .db.models import ManualPick
    from .picks import existing_pick

    if ctx.slot is None:
        return Result(False, "slot unknown")
    if ctx.slot not in SCHEDULED_SLOTS:
        n = (
            ctx.session.query(ManualPick.id)
            .filter(ManualPick.is_paper.is_(True), ManualPick.placed_at >= ctx.run_started_at)
            .count()
        )
        return Result(n == 0, f"{ctx.slot} build logged {n} paper picks (wants 0)")
    p = _card_payload(ctx)
    if p is None:
        return Result(False, "no card row")
    window = PAPER_WINDOW_HOURS.get(ctx.slot)
    expected: List[int] = []
    for it in p.get("items") or []:
        if not it.get("qualifies"):
            continue
        kick = _parse_kick(it.get("kick"))
        if window is not None and kick is not None:
            if kick - ctx.run_started_at > timedelta(hours=window):
                continue
        expected.append(int(it["game_id"]))
    missing = [
        gid for gid in expected if existing_pick(ctx.session, gid, "1H", is_paper=True) is None
    ]
    win = "rest of week" if window is None else f"{window:g}h"
    detail = f"{len(expected) - len(missing)}/{len(expected)} qualifying items in window ({win}) have a paper pick"
    if missing:
        detail += " missing " + ",".join(str(g) for g in missing[:6])
    return Result(not missing, detail)


def card_sweep_reached_slate(ctx: Ctx) -> Result:
    st = ctx.status_files.get("sweep")
    outcome = ctx.outcomes.get("sweep", "")
    if st is None:
        if outcome == "skipped":
            return Result(True, "sweep skipped, today's snapshot already on file")
        return Result(False, f"no sweep status file (sweep step outcome={outcome or 'unknown'})")
    polled = int(st.get("events_polled") or 0)
    in_window = int(st.get("events_in_window") or 0)
    complete = st.get("complete") is True
    detail = f"complete={str(complete).lower()} polled={polled}/{in_window} credits={st.get('credits_spent')}"
    if st.get("reason"):
        detail += f" reason={st.get('reason')}"
    return Result(complete and polled >= in_window, detail)


def card_info(ctx: Ctx) -> Dict[str, str]:
    p = _card_payload(ctx)
    out = {
        "sweep": ctx.outcomes.get("sweep", "?"),
        "preview": ctx.outcomes.get("preview", "?"),
    }
    if p is not None:
        items = p.get("items") or []
        out["early_season_held"] = str(
            sum(
                1
                for it in items
                if it.get("blocker") == "early_season" or it.get("gate_blocker") == "early_season"
            )
        )
        out["bets"] = str((p.get("counts") or {}).get("bet", "?"))
        # Games whose newest Hard Rock quote was an alternate line, shown at the
        # last main line and kept out of every gate (card.market_read).
        out["hr_alt_ignored"] = str(sum(1 for it in items if it.get("hr_alt_line") is not None))
    return out


# --------------------------------------------------------------------------- #
# grade
# --------------------------------------------------------------------------- #
def grade_completed_this_run(ctx: Ctx) -> Result:
    value, at = read_gauge(ctx.session, LAST_GRADE_COMPLETED_AT)
    ok = at is not None and at >= ctx.run_started_at
    return Result(
        ok,
        f"{LAST_GRADE_COMPLETED_AT} updated_at={_iso(at)} run started {_iso(ctx.run_started_at)}",
    )


def grade_finals_landed(ctx: Ctx) -> Result:
    """The board's stale-results predicate (web/lib/boardHealth.ts getGradeHealth):
    a game THE MODEL RATED (a game_records row), kicked off > STALE_AFTER_HOURS
    ago, still without a final."""
    from sqlalchemy import exists

    from .db.models import Game, GameRecord

    cutoff = ctx.now - timedelta(hours=STALE_AFTER_HOURS)
    q = ctx.session.query(Game.id).filter(
        Game.season == ctx.season,
        Game.home_points.is_(None),
        Game.start_date < cutoff,
        exists().where(GameRecord.game_id == Game.id),
    )
    n = q.count()
    return Result(n == 0, f"{n} rated games kicked off >{STALE_AFTER_HOURS}h ago without a final")


def grade_records_graded(ctx: Ctx) -> Result:
    from .db.models import Game, GameRecord

    n = (
        ctx.session.query(GameRecord.id)
        .join(Game, Game.id == GameRecord.game_id)
        .filter(
            GameRecord.season == ctx.season,
            GameRecord.graded_at.is_(None),
            Game.first_half_total.isnot(None),
        )
        .count()
    )
    return Result(n == 0, f"{n} game_records with a first-half total still ungraded")


def grade_picks_graded(ctx: Ctx) -> Result:
    from .db.models import Game, ManualPick

    n = (
        ctx.session.query(ManualPick.id)
        .join(Game, Game.id == ManualPick.game_id)
        .filter(
            ManualPick.season == ctx.season,
            (ManualPick.graded.is_(False)) | (ManualPick.graded.is_(None)),
            Game.first_half_total.isnot(None),
        )
        .count()
    )
    return Result(n == 0, f"{n} picks on a played game still ungraded")


def grade_postmortem_written(ctx: Ctx) -> Result:
    from .db.models import PostMortemRun

    scope = f"live_{ctx.season}"
    row = (
        ctx.session.query(PostMortemRun)
        .filter(PostMortemRun.scope == scope, PostMortemRun.computed_at >= ctx.run_started_at)
        .order_by(PostMortemRun.computed_at.desc())
        .first()
    )
    if row is None:
        return Result(
            False, f"no postmortem_runs row scope={scope} since {_iso(ctx.run_started_at)}"
        )
    return Result(True, f"scope={scope} computed_at={_iso(row.computed_at)} n_games={row.n_games}")


def grade_info(ctx: Ctx) -> Dict[str, str]:
    from .db.models import GameRecord

    zero = (
        ctx.session.query(GameRecord.id)
        .filter(GameRecord.graded_at >= ctx.run_started_at, GameRecord.first_half_total == 0)
        .count()
    )
    out = {"zero_halves_graded": str(zero)}
    for step in ("backfill", "espn", "pbp", "ledger", "pm"):
        if step in ctx.outcomes:
            out[step] = ctx.outcomes[step]
    return out


# --------------------------------------------------------------------------- #
# sunday
# --------------------------------------------------------------------------- #
def sunday_fg_snapshot_today(ctx: Ctx) -> Result:
    from .db.models import OddsSnapshot

    since = et_midnight_as_naive_utc(ctx.now)
    n = (
        ctx.session.query(OddsSnapshot.id)
        .filter(OddsSnapshot.market == FULL_GAME_MARKET, OddsSnapshot.captured_at >= since)
        .count()
    )
    return Result(n > 0, f"{n} full-game snapshots since ET midnight ({_iso(since)})")


def _predictions_today(ctx: Ctx, derived: bool) -> int:
    from .db.models import Game, Prediction

    since = et_midnight_as_naive_utc(ctx.now)
    q = (
        ctx.session.query(Prediction.id)
        .join(Game, Game.id == Prediction.game_id)
        .filter(Game.season == ctx.season, Game.week == ctx.week, Prediction.created_at >= since)
    )
    if derived:
        q = q.filter(Prediction.model_version == DERIVED_LINES_MODEL_VERSION)
    else:
        q = q.filter(Prediction.model_version != DERIVED_LINES_MODEL_VERSION)
    return q.count()


def sunday_predictions_today(ctx: Ctx) -> Result:
    n = _predictions_today(ctx, derived=False)
    return Result(n > 0, f"{n} model predictions for {ctx.season} w{ctx.week} since ET midnight")


def sunday_derived_lines_posted(ctx: Ctx) -> Result:
    n = _predictions_today(ctx, derived=True)
    return Result(n > 0, f"{n} derived_lines rows for {ctx.season} w{ctx.week} since ET midnight")


def sunday_pace_coverage(ctx: Ctx) -> Result:
    from .db.models import TeamTempo

    slate = _fbs_slate(ctx)
    teams: Set[str] = set()
    for _gid, h, a in slate:
        teams.add(h)
        teams.add(a)
    if not teams:
        return Result(False, "no FBS games on the slate")
    with_pace = {
        t
        for (t,) in ctx.session.query(TeamTempo.team)
        .filter(
            TeamTempo.season == ctx.season,
            TeamTempo.week == ctx.week,
            TeamTempo.seconds_per_play.isnot(None),
        )
        .distinct()
    }
    covered = len(teams & with_pace)
    share = covered / len(teams)
    detail = f"{covered}/{len(teams)} slate teams have a pace row ({share:.0%}, floor {PACE_COVERAGE_MIN:.0%})"
    if ctx.cache.get("fbs_note"):
        detail += f", {ctx.cache['fbs_note']}"
    return Result(share >= PACE_COVERAGE_MIN, detail)


def sunday_weather_coverage(ctx: Ctx) -> Result:
    from .db.models import Weather

    slate = _fbs_slate(ctx)
    if not slate:
        return Result(False, "no FBS games on the slate")
    ids = [gid for gid, _h, _a in slate]
    with_wx = ctx.session.query(Weather.game_id).filter(Weather.game_id.in_(ids)).count()
    share = with_wx / len(ids)
    detail = f"{with_wx}/{len(ids)} FBS games have a weather row ({share:.0%}, floor {WX_COVERAGE_MIN:.0%})"
    if ctx.cache.get("fbs_note"):
        detail += f", {ctx.cache['fbs_note']}"
    return Result(share >= WX_COVERAGE_MIN, detail)


def sunday_info(ctx: Ctx) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for key in ("NEED_CAPTURE", "NEED_SCORE"):
        if ctx.env.get(key):
            out[key.lower()] = ctx.env[key]
    for step in ("pace", "weather"):
        if step in ctx.outcomes:
            out[step] = ctx.outcomes[step]
    return out


# --------------------------------------------------------------------------- #
# lines_watch
# --------------------------------------------------------------------------- #
def _close_polled(ctx: Ctx) -> int:
    st = ctx.status_files.get("close")
    return int(st.get("events_polled") or 0) if st else 0


def lines_watch_close_polled(ctx: Ctx) -> Result:
    st = ctx.status_files.get("close")
    if st is None:
        return Result(False, "no close status file")
    polled = int(st.get("events_polled") or 0)
    in_window = int(st.get("events_in_window") or 0)
    detail = f"polled={polled}/{in_window} complete={str(st.get('complete') is True).lower()}"
    if st.get("reason"):
        detail += f" reason={st.get('reason')}"
    return Result(polled > 0 or in_window == 0, detail)


def lines_watch_hr_rows_touched(ctx: Ctx) -> Result:
    """A close poll that reached an event wrote or re-saw a Hard Rock 1H row: an
    unchanged number writes no row and stamps last_seen_at (the close time)."""
    from .db.models import OddsSnapshot

    polled = _close_polled(ctx)
    if polled == 0:
        return Result(True, "n/a, no events polled")
    n = (
        ctx.session.query(OddsSnapshot.id)
        .filter(
            OddsSnapshot.book == HR_BOOK_KEY,
            OddsSnapshot.market == FIRST_HALF_MARKET,
            (OddsSnapshot.captured_at >= ctx.run_started_at)
            | (OddsSnapshot.last_seen_at >= ctx.run_started_at),
        )
        .count()
    )
    return Result(
        n > 0, f"{n} Hard Rock 1H rows captured or re-seen since {_iso(ctx.run_started_at)}"
    )


def lines_watch_close_gauge_written(ctx: Ctx) -> Result:
    polled = _close_polled(ctx)
    if polled == 0:
        return Result(True, "n/a, no events polled")
    _value, at = read_gauge(ctx.session, LAST_CLOSE_CAPTURE_AT)
    ok = at is not None and at >= ctx.run_started_at
    return Result(ok, f"{LAST_CLOSE_CAPTURE_AT} updated_at={_iso(at)}")


def lines_watch_info(ctx: Ctx) -> Dict[str, str]:
    st = ctx.status_files.get("close")
    out: Dict[str, str] = {}
    if st:
        out["polled"] = str(st.get("events_polled", "?"))
        out["credits"] = str(st.get("credits_spent", "?"))
    return out


# --------------------------------------------------------------------------- #
# The contracts
# --------------------------------------------------------------------------- #
CONTRACTS: Dict[str, Contract] = {
    "card": Contract(
        job="card",
        workflow="card.yml",
        window="tue_pm / thu_pm / fri_pm 3:45-5:15pm ET, sat_am 7:45-9:15am ET (beatvegas/ci.py)",
        artifacts=(
            "cards row",
            "manual_picks paper rows (scheduled slots)",
            "odds_snapshots 1H sweep",
        ),
        inputs=("SLOT", "SEASON", "WEEK", "OUTCOME_SWEEP", "OUTCOME_PREVIEW", "OUTCOME_BUILD"),
        checks=(
            Check(
                "card.row_this_run",
                "failed",
                "a `cards` row for (SEASON, WEEK) with built_at >= RUN_STARTED_AT whose payload.slot == SLOT",
                card_row_this_run,
            ),
            Check(
                "card.status_clean",
                "degraded",
                "that row's payload.status is the slot's clean status (ci.CARD_STATUS_BY_SLOT) and payload.degraded is empty",
                card_status_clean,
            ),
            Check(
                "card.hr_priced_floor",
                "degraded",
                "items with a Hard Rock 1H line >= HR_PRICED_FLOOR [10]",
                card_hr_priced_floor,
            ),
            Check(
                "card.paper_logged_iff_window",
                "degraded",
                "scheduled slot: every qualifying item inside the slot's paper window has a paper pick; manual: zero paper picks placed since RUN_STARTED_AT",
                card_paper_logged_iff_window,
            ),
            Check(
                "card.sweep_reached_slate",
                "degraded",
                "the sweep status file says complete and events_polled >= events_in_window (a missing file is a miss unless the sweep step was skipped)",
                card_sweep_reached_slate,
            ),
        ),
        failure_modes=(
            FailureMode(
                "2026-09-10",
                "a mid-sweep Odds API 5xx killed the job before build_card ran: no card at all. The sweep now continues on error; a partial sweep ships the card degraded.",
                ("card.row_this_run", "card.status_clean", "card.sweep_reached_slate"),
            ),
            FailureMode(
                "2026-09-21",
                "the first build of the week (nothing cached, 57 fresh previews) hit the 15-minute job timeout; GitHub reported `cancelled` and no card shipped. The timeout is 30 now. A cancelled job only runs its always() steps inside GitHub's grace window, so this step may never run on a timeout -- the board's buildStatus (missed build) is the check that always fires.",
                ("card.row_this_run",),
            ),
            FailureMode(
                "2026-09-13",
                "the paper window gave each slot the gap to the next build, so Friday's three clean BETs were never logged and the Saturday build claimed the whole slate; and a `manual` refresh logging paper picks would freeze the week at that moment's lines.",
                ("card.paper_logged_iff_window",),
            ),
            FailureMode(
                "2026-09-09",
                "a Vercel tick outside its window, or a GitHub cron running the build instead of the Vercel dispatch: invisible in the runs API. The board's `dispatch:<job>` warning covers it; the note carries `event=` so the trigger is on record.",
                (),
            ),
            FailureMode(
                "2026-09-20",
                "`early_season` held 10 games on the Friday card (an FCS opener leaves a team at 1 FBS game). Correct behaviour, so it is info (`early_season_held=N`), never a miss.",
                (),
            ),
            FailureMode(
                "2026-09-25",
                "the Odds API served Hard Rock alternate lines (2-3 pts off the field at -145..-160) as its 1H total; 20 passed the general -160 price bar and 12 paper picks were logged on them. The card now keeps them out of every gate (`devig.is_hr_rung`); a count is info (`hr_alt_ignored=N`), never a miss.",
                (),
            ),
        ),
        info=card_info,
    ),
    "grade": Contract(
        job="grade",
        workflow="grade.yml",
        window="daily, 10:30Z and 16:00Z crons plus the Vercel dispatch; skipped when a run completed in the last 4 h",
        artifacts=(
            "games finals",
            "results / manual_picks graded",
            "game_records graded",
            "postmortem_runs live_<season>",
            "last_grade_completed_at gauge",
        ),
        inputs=(
            "SEASON",
            "OUTCOME_BACKFILL",
            "OUTCOME_ESPN",
            "OUTCOME_PBP",
            "OUTCOME_LEDGER",
            "OUTCOME_PM",
        ),
        checks=(
            Check(
                "grade.completed_this_run",
                "failed",
                "the `last_grade_completed_at` gauge was written after RUN_STARTED_AT (the fatal grading steps all ran)",
                grade_completed_this_run,
            ),
            Check(
                "grade.finals_landed",
                "degraded",
                "zero rated games (a game_records row) in SEASON with home_points NULL that kicked off more than STALE_AFTER_HOURS [18] hours ago -- the board's stale-results predicate",
                grade_finals_landed,
            ),
            Check(
                "grade.records_graded",
                "degraded",
                "zero game_records in SEASON with graded_at NULL whose game has a first_half_total",
                grade_records_graded,
            ),
            Check(
                "grade.picks_graded",
                "degraded",
                "zero manual_picks in SEASON with graded false/NULL whose game has a first_half_total",
                grade_picks_graded,
            ),
            Check(
                "grade.postmortem_written",
                "degraded",
                "a postmortem_runs row with scope == live_<SEASON> and computed_at >= RUN_STARTED_AT",
                grade_postmortem_written,
            ),
            Check(
                "grade.reference_cache_populated",
                "degraded",
                "the five CFBD reference files (sp/talent/roster/returning/adv) for SEASON-1 exist in data/cache/ at > REFERENCE_CACHE_MIN_BYTES [1024] bytes",
                _reference_cache_populated,
            ),
        ),
        failure_modes=(
            FailureMode(
                "2026-09-12",
                "CFBD returned 429 on the first, unguarded call and grade.yml failed four runs straight; week 2 sat with finals for 14 of 303 games and 0 of 31 picks graded for two days.",
                ("grade.completed_this_run", "grade.finals_landed", "grade.picks_graded"),
            ),
            FailureMode(
                "2026-09-16",
                "the CFBD reference cache had saved an EMPTY payload all season (the first job of each ISO week made no CFBD calls), so every later run re-fetched ~22 reference calls against a 3,000-call month.",
                ("grade.reference_cache_populated",),
            ),
            FailureMode(
                "2026-09-22",
                "the four-hour probe matched scope = 'live' while the rows are written as live_<season>, so it matched nothing and never skipped. The check compares the exact scope string.",
                ("grade.postmortem_written",),
            ),
            FailureMode(
                "2026-09-20",
                "fifteen 0-0 first halves on file looked like the ESPN false zero and were all real (PR #176). Zero halves graded this run are counted as info (`zero_halves_graded=N`), never judged.",
                (),
            ),
        ),
        info=grade_info,
    ),
    "sunday": Contract(
        job="sunday",
        workflow="sunday.yml",
        window="Sunday 18:00Z / 19:00Z / 20:30Z crons plus the Vercel dispatch, 1-5pm ET",
        artifacts=(
            "odds_snapshots full_game_total",
            "team_tempo (season, week)",
            "weather rows",
            "predictions (model + derived_lines)",
        ),
        inputs=("SEASON", "WEEK", "NEED_CAPTURE", "NEED_SCORE", "OUTCOME_PACE", "OUTCOME_WEATHER"),
        checks=(
            Check(
                "sunday.fg_snapshot_today",
                "failed",
                "at least one odds_snapshots row with market full_game_total captured since ET midnight",
                sunday_fg_snapshot_today,
            ),
            Check(
                "sunday.predictions_today",
                "failed",
                "at least one predictions row for the week's games with model_version != derived_lines created since ET midnight",
                sunday_predictions_today,
            ),
            Check(
                "sunday.derived_lines_posted",
                "degraded",
                "at least one predictions row for the week's games with model_version == derived_lines created since ET midnight",
                sunday_derived_lines_posted,
            ),
            Check(
                "sunday.pace_coverage",
                "degraded",
                "share of the week's FBS slate teams with a team_tempo(SEASON, WEEK) row carrying seconds_per_play >= PACE_COVERAGE_MIN [0.8]",
                sunday_pace_coverage,
            ),
            Check(
                "sunday.weather_coverage",
                "degraded",
                "share of the week's FBS games with a weather row >= WX_COVERAGE_MIN [0.8]",
                sunday_weather_coverage,
            ),
            Check(
                "sunday.reference_cache_populated",
                "degraded",
                "the five CFBD reference files for SEASON-1 exist in data/cache/ at > REFERENCE_CACHE_MIN_BYTES [1024] bytes",
                _reference_cache_populated,
            ),
        ),
        failure_modes=(
            FailureMode(
                "2026-09-22",
                "B-SERVE: the live model scored every upcoming game with 57 of 115 inputs NaN. weekly_update.py now FAILS a scoring run whose target rows are >90% NaN on a column training has, which leaves no prediction row for the day.",
                ("sunday.predictions_today",),
            ),
            FailureMode(
                "2026-09-13",
                "four Sunday ticks each re-ran the whole job for one capture (~1,150 Open-Meteo calls). The need_capture / need_score probes fixed the spend; the checks read the day's facts, not this run's, so a correctly skipped tick still passes.",
                ("sunday.fg_snapshot_today", "sunday.predictions_today"),
            ),
            FailureMode(
                "2026-09-16",
                "the CFBD reference cache saved an empty payload all season.",
                ("sunday.reference_cache_populated",),
            ),
        ),
        info=sunday_info,
    ),
    "lines_watch": Contract(
        job="lines_watch",
        workflow="lines_watch.yml",
        window="every 30 min in the kickoff windows (1h_close); the free /events pre-check skips a slot with nothing kicking off in 75 min",
        artifacts=("odds_snapshots 1H rows or last_seen_at stamps", "last_close_capture_at gauge"),
        inputs=("MARKET",),
        checks=(
            Check(
                "lines_watch.close_polled",
                "degraded",
                "the close status file exists and says events_polled > 0, or events_in_window == 0",
                lines_watch_close_polled,
            ),
            Check(
                "lines_watch.hr_rows_touched",
                "degraded",
                "when events were polled: an odds_snapshots row with book hardrockbet and market 1H_total has captured_at or last_seen_at >= RUN_STARTED_AT",
                lines_watch_hr_rows_touched,
            ),
            Check(
                "lines_watch.close_gauge_written",
                "degraded",
                "when events were polled: the `last_close_capture_at` gauge was written after RUN_STARTED_AT",
                lines_watch_close_gauge_written,
            ),
        ),
        failure_modes=(
            FailureMode(
                "2026-08-28",
                "GitHub's cron fired 2 of 19 scheduled close slots; a dead run of them is what the board's `close` gauge warning (CLOSE_CAPTURE_MAX_AGE_H) covers, which is why no check here is failed-severity.",
                ("lines_watch.close_polled", "lines_watch.close_gauge_written"),
            ),
            FailureMode(
                "2026-09-09",
                "a Hard Rock book key drift would make a close poll write no hardrockbet row while spending every credit; poll_lines warns, this makes it a verdict.",
                ("lines_watch.hr_rows_touched",),
            ),
        ),
        info=lines_watch_info,
    ),
}


def all_check_ids() -> List[str]:
    return [c.id for k in CONTRACTS.values() for c in k.checks]


# --------------------------------------------------------------------------- #
# Evaluation
# --------------------------------------------------------------------------- #
def evaluate(contract: Contract, ctx: Ctx) -> Tuple[Verdict, List[Tuple[Check, Result]]]:
    """Run every check; a check that raises is a miss (not a positive fact)."""
    results: List[Tuple[Check, Result]] = []
    for check in contract.checks:
        try:
            res = check.fn(ctx)
        except Exception as e:  # noqa: BLE001 - the verdict must always be written
            res = Result(False, f"check raised {type(e).__name__}: {str(e)[:60]}")
        results.append((check, Result(bool(res.ok), _clean(res.detail))))
    if any(c.severity == "failed" and not r.ok for c, r in results):
        return "failed", results
    if any(not r.ok for _c, r in results):
        return "degraded", results
    return "ok", results


def verdict_note(job: str, ctx: Ctx, results: List[Tuple[Check, Result]]) -> str:
    """`run=<id> event=<name> slot=<slot> miss=<id>(<detail>);... info=k=v ...`,
    at most NOTE_MAX_CHARS. The board parses `run=` (link to the run) and
    `miss=` (the items); the rest is for a human reading the gauge row."""
    parts = [
        f"run={ctx.env.get('GITHUB_RUN_ID') or '-'}",
        f"event={ctx.env.get('GITHUB_EVENT_NAME') or '-'}",
    ]
    if ctx.slot:
        parts.append(f"slot={ctx.slot}")
    if ctx.market:
        parts.append(f"market={ctx.market}")
    misses = [(c.id, r.detail) for c, r in results if not r.ok]
    if misses:
        parts.append("miss=" + ";".join(f"{cid}({detail[:90]})" for cid, detail in misses))
    contract = CONTRACTS.get(job)
    info: Dict[str, str] = {}
    if contract is not None:
        try:
            info = contract.info(ctx)
        except Exception as e:  # noqa: BLE001 - info is a courtesy
            info = {"info_error": type(e).__name__}
    if info:
        parts.append("info=" + " ".join(f"{k}={_clean(str(v))}" for k, v in sorted(info.items())))
    note = " ".join(parts)
    if len(note) > NOTE_MAX_CHARS:
        note = note[: NOTE_MAX_CHARS - 3] + "..."
    return note


# --------------------------------------------------------------------------- #
# docs/HEALTH.md
# --------------------------------------------------------------------------- #
CONTRACTS_BEGIN = "<!-- contracts:begin -->"
CONTRACTS_END = "<!-- contracts:end -->"


def render_contracts() -> str:
    """The generated block of docs/HEALTH.md. Deterministic: contracts in
    declaration order, one `### <job>` heading each (the anchor the board links
    to as docs/HEALTH.md#<job>)."""
    lines: List[str] = [
        CONTRACTS_BEGIN,
        "<!-- Generated by `python -m beatvegas.health --render-md docs/HEALTH.md`. Do not edit by hand. -->",
        "",
        "Parameters: " + ", ".join(f"`{k} = {v}`" for k, v in PARAMETERS.items()),
        "",
    ]
    for c in CONTRACTS.values():
        lines += [
            f"### {c.job}",
            "",
            f"- Workflow: `.github/workflows/{c.workflow}`",
            f"- Window: {c.window}",
            "- Artifacts: " + ", ".join(f"`{a}`" for a in c.artifacts),
            "- Inputs (env, beside `SKIPPED` and `RUN_STARTED_AT`): "
            + ", ".join(f"`{i}`" for i in c.inputs),
            "",
            "| Check | Severity | Positive fact |",
            "|---|---|---|",
        ]
        for ch in c.checks:
            lines.append(f"| `{ch.id}` | {ch.severity} | {ch.fact} |")
        lines += ["", "Failure modes on record:", ""]
        for fm in c.failure_modes:
            caught = ", ".join(f"`{i}`" for i in fm.caught_by) if fm.caught_by else "info only"
            lines.append(f"- **{fm.date}** -- {fm.what} Caught by: {caught}.")
        lines.append("")
    lines.append(CONTRACTS_END)
    return "\n".join(lines) + "\n"


def render_into(text: str) -> str:
    """Replace the block between the markers in a HEALTH.md body."""
    start = text.find(CONTRACTS_BEGIN)
    end = text.find(CONTRACTS_END)
    if start < 0 or end < 0 or end < start:
        raise ValueError("docs/HEALTH.md is missing the contracts:begin / contracts:end markers")
    end += len(CONTRACTS_END)
    # The block is rendered with its own trailing newline; keep whatever
    # followed the end marker in the file.
    tail = text[end:]
    if tail.startswith("\n"):
        tail = tail[1:]
    return text[:start] + render_contracts() + tail


def _main(argv: Optional[List[str]] = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Render the health contracts into docs/HEALTH.md.")
    ap.add_argument("--render-md", metavar="PATH", help="regenerate the contracts block in PATH")
    args = ap.parse_args(argv)
    if args.render_md:
        p = Path(args.render_md)
        p.write_text(render_into(p.read_text()))
        print(f"rendered {len(CONTRACTS)} contracts into {p}")
        return 0
    sys.stdout.write(render_contracts())
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
